sudo: required
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t "$DOCKER_USERNAME"/complex-fibonacci -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true "$DOCKER_USERNAME"/complex-fibonacci npm test

after_success:
  - docker build -t "$DOCKER_USERNAME"/complex-fibonacci-client ./client
  - docker build -t "$DOCKER_USERNAME"/complex-fibonacci-nginx ./nginx
  - docker build -t "$DOCKER_USERNAME"/complex-fibonacci-server ./server
  - docker build -t "$DOCKER_USERNAME"/complex-fibonacci-worker ./worker
  # LOGIN TO DOCKER CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # PUSH THE IMAGES TO DOCKER HUB
  - docker push "$DOCKER_USERNAME"/complex-fibonacci-client
  - docker push "$DOCKER_USERNAME"/complex-fibonacci-nginx
  - docker push "$DOCKER_USERNAME"/complex-fibonacci-server
  - docker push "$DOCKER_USERNAME"/complex-fibonacci-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app:  complex-fibonacci
  env:  ComplexFibonacci-env
  bucket_name:  elasticbeanstalk-us-east-2-636982052424
  bucket_path:  complex-fibonacci
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"